### ISSUE TITLE
能完善前端部分的话我可完成后端。

### ISSUE THREAD

**Issue by 308066400** [fattigerlee/Poker#1]
能完善前端部分的话我可完成后端。
Cocos Creator不支持linux，有h5的前端就好了，而且h5比较接触多较熟悉。

**Comment by fattigerlee** [comment]
这个游戏后端我是完成了的,只是部分核心算法开源了

**Comment by 308066400** [comment]
有找到开源可用的德州客户端吗？

**Comment by 308066400** [comment]
已经找到一份完整的德州包含前后端。。。正在调试。。。感谢回复！
